# Generated by Django 3.2.18 on 2023-04-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('cost_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Foodtype',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('pay_time', models.DateTimeField(null=True)),
                ('is_pay', models.BooleanField(default=False)),
                ('food_amount', models.IntegerField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('table_id', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('citizenID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=20)),
                ('born_date', models.DateField(null=True)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Table',
            fields=[
                ('ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OrderSystem.staff')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('sum_price', models.FloatField(default=0)),
                ('status', models.IntegerField(choices=[(0, '后厨未接单'), (1, '后厨在准备'), (2, '等待上菜'), (3, '上菜完成')], default=0)),
                ('start_cook_time', models.TimeField(null=True)),
                ('end_cook_time', models.TimeField(null=True)),
                ('comment', models.CharField(max_length=50)),
                ('foodID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OrderSystem.food')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderSystem.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OrderSystem.staff'),
        ),
        migrations.AddField(
            model_name='food',
            name='foodType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='OrderSystem.foodtype'),
        ),
    ]
