# Generated by Django 3.2.17 on 2024-05-29 13:50

import OrderSystem.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderSystem', '0002_auto_20240518_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=OrderSystem.models.food_image_path, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='orderhotfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot', to='OrderSystem.food', verbose_name='菜品'),
        ),
    ]
